# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTasks',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
