# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-18 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='birth',
            field=models.DateTimeField(default='1990-1-1', verbose_name='Birthday'),
        ),
    ]
