# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_info_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
