# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-23 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_todotasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoTasks',
        ),
    ]
